name: CI

env:
  NODE_VERSION: "18"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

        run: pnpm install
        run: pnpm build

  unit-test:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

        run: pnpm test

  integration-tests:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v3
        uses: cypress-io/github-action@v6
        with:
          build: pnpm run build
          start: pnpm start
          browser: chrome
